---
title: "World Tea Production FAO 2006-2013"
author: "Cameron Williams"
date: "1/23/2022"
output:
  pdf_document: default
  html_document: default
---

```{r}
install.packages("readxl", repos = "http://cran.us.r-project.org")
library(readxl)
WTP2006_2013 <- read_excel("...")
str(WTP2006_2013)
WTP2006_2013 <- WTP2006_2013[-1:-1,]
View(WTP2006_2013)
colnames(WTP2006_2013)
```

```{r}
cnames <- colnames(WTP2006_2013)
cnames[1] <- "Names and Regions"
cnames[2] <- "2006-2008"
cnames[3] <- "2009"
cnames[4] <- "2010"
cnames[5] <- "2011"
cnames[6] <- "2012"
cnames[7] <- "2013"
cnames
colnames(WTP2006_2013) <- cnames
colnames(WTP2006_2013)
str(WTP2006_2013)
```

```{r}
WTP2006_2013$`2006-2008` <- as.numeric(WTP2006_2013$`2006-2008`)
str(WTP2006_2013)

plot(WTP2006_2013$`2006-2008`)
plot(WTP2006_2013$`2011`)
```

```{r}
hist(WTP2006_2013$`2006-2008`)
hist(WTP2006_2013$`2009`)
hist(WTP2006_2013$`2010`)
hist(WTP2006_2013$`2011`)
hist(WTP2006_2013$`2012`)
hist(WTP2006_2013$`2013`)

plot(WTP2006_2013$`2006-2008`)
plot(WTP2006_2013$`2009`)

install.packages("ggplot2", repos = "http://cran.us.r-project.org")
library(ggplot2)
theme_set(
  theme_classic() +
    theme(legend.position = "top")
)
```

```{r}
install.packages("tidyr", repos = "http://cran.us.r-project.org")
library(tidyr)

#creating a consolidated view of data and creating plot of the first half of records
WTP2006_2013head <- gather(head(WTP2006_2013), key = "measure", value = "value", 
                           c("2006-2008", "2009", "2010", "2011", "2012", "2013"))

variable_names <- list(
  "2006-2008" = "Tea Prod. in 2006-2008",
  "2009" = "Tea Prod. 2009",
  "2010" = "Tea Prod. 2010",
  "2011" = "Tea Prod. 2011",
  "2012" = "Tea Prod. 2012",
  "2013" = "Tea Prod. 2013"
)
```

```{r}
variable_labeller <- function(variable, value){
  return(variable_names[value])
}

library(ggplot2)
w <- ggplot(WTP2006_2013head, aes(x=WTP2006_2013head$`Names and Regions`, y=value))+
  geom_bar(stat = "identity", fill = "steelblue")+
  theme_minimal()+
  theme(axis.text = element_text(angle = 60, hjust = 1))+
  facet_grid(~measure)

w + labs(x = "Tea Production: Names and Regions", y = "Tea Production(Tonnes)")
```
